# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Disable metrics
opt_out_usage

default_platform(:ios)

platform :ios do
    before_all do
      app_store_connect_api_key(
        key_id: "XXXXX", # App Manager Role
        issuer_id: "XXXXX",
        key_filepath: "/Users/XXXXX/AuthKey_XXXXX.p8",
        in_house: false
      )
    end
    
  desc "Verify and update signing certificates"
  lane :sign do
    match(
      readonly: false, # do not verify certificates on Apple Developer Portal
      git_url: "https://github.com/XXXXX/AppleCertificates.git",
      git_branch: "main",
      app_identifier: "com.starkdmi.TGStickers",
      type: "appstore"
    ) 
  end

  desc "Build Application"
  lane :build do
    # increment_build_number
    sign

    gym(
      scheme: "TGStickersImport",
      # configuration: "Release",
      # clean: true,
      # silent: true,
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]
      },
      output_directory: "./build/",
      output_name: "TGStickers.ipa"
    )
  end

  desc "Capture and Process the Screenshots"
  lane :screenshots do

    # https://docs.fastlane.tools/actions/snapshot/#parameters
    snapshot(
      scheme: "TGStickersImport",
      devices: [
        "iPhone 8 Plus",
        "iPhone 11 Pro Max",
        "iPad Pro (12.9-inch) (4th generation)",
      ],
      languages: [
        "en-US",
        # "de-DE",
      ],
      headless: true, # won't work
      override_status_bar: true,
      dark_mode: true,
      skip_open_summary: true,
      # launch_arguments: ["SKIP_ANIMATIONS"],
    )

     # https://docs.fastlane.tools/actions/frameit/#parameters
     # frameit(white: true, path: "fastlane/screenshots") # white, silver, rose_gold, gold
  end

  desc "Upload Application to Testflight beta testing"
  lane :beta do
    #increment_build_number
    build

    #latest_testflight_build_number

    # https://docs.fastlane.tools/actions/upload_to_testflight/#parameters
    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )
  end

  desc "Release Application to App Store with Metadata and Screenshots"
  lane :release do
    #increment_build_number
    build
    #screenshots

    # https://docs.fastlane.tools/actions/deliver/#parameters
    deliver(
      submit_for_review: false,
      # force: true, # Set to true to skip verification of HTML preview
      # platform: "ios", # ios by default
      precheck_include_in_app_purchases: false
    )
  end
end
